### ISSUE TITLE
worker hangs

### ISSUE THREAD

**Issue by saggit** [RichardKnop/machinery#150]
hello

I have a  worker running some tasks, but most time, the worker is idle, may be weeks or more.
and I find the worker just `dead` with no respond even with Ctrl + c.

some details:
golang 1.8.1 use rabbitmq as backend and redis as result backend
cross compile build on mac and running on centos7

here is some details when i press control+backslash

`^CWARNING: 2017/07/19 16:36:22 worker.go:59 Signal received: interrupt. Quitting the worker                                     [52/1199]^C^C^C^\SIGQUIT: quit
PC=0x4564d3 m=1 sigcode=128

goroutine 0 [idle]:
runtime.futex(0xdcb018, 0x0, 0xc42003dec0, 0x0, 0xc400000000, 0x456166, 0x3c, 0x0, 0xc42003df08, 0x40d8d0, ...)
        /usr/local/Cellar/go/1.8.1/libexec/src/runtime/sys_linux_amd64.s:423 +0x23
runtime.futexsleep(0xdcb018, 0x0, 0xdf8475800)
        /usr/local/Cellar/go/1.8.1/libexec/src/runtime/os_linux.go:62 +0xd7
runtime.notetsleep_internal(0xdcb018, 0xdf8475800, 0x0)
        /usr/local/Cellar/go/1.8.1/libexec/src/runtime/lock_futex.go:174 +0xd0
runtime.notetsleep(0xdcb018, 0xdf8475800, 0xcfb0b73a6da00)
        /usr/local/Cellar/go/1.8.1/libexec/src/runtime/lock_futex.go:194 +0x56
runtime.sysmon()
        /usr/local/Cellar/go/1.8.1/libexec/src/runtime/proc.go:3805 +0x135
runtime.mstart1()
        /usr/local/Cellar/go/1.8.1/libexec/src/runtime/proc.go:1179 +0x11e
runtime.mstart()
        /usr/local/Cellar/go/1.8.1/libexec/src/runtime/proc.go:1149 +0x64

goroutine 1 [chan receive, 6226 minutes]:
github.com/RichardKnop/machinery/v1.(*Worker).Launch(0xc4201644a0, 0x0, 0xc420135f78)
        /Users/lt/go/src/github.com/RichardKnop/machinery/v1/worker.go:64 +0x446
main.main()
        /Users/lt/MEGAsync/source/golang/src/github.com/saggit/TQ/worker.go:87 +0x31

goroutine 18 [syscall, 12 minutes]:
os/signal.signal_recv(0xd91fe0)
        /usr/local/Cellar/go/1.8.1/libexec/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
        /usr/local/Cellar/go/1.8.1/libexec/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /usr/local/Cellar/go/1.8.1/libexec/src/os/signal/signal_unix.go:28 +0x41
goroutine 19 [select, 6226 minutes, locked to thread]:
runtime.gopark(0xae7960, 0x0, 0xac4faf, 0x6, 0x18, 0x2)
        /usr/local/Cellar/go/1.8.1/libexec/src/runtime/proc.go:271 +0x13a
runtime.selectgoImpl(0xc420040f50, 0x0, 0x18)
        /usr/local/Cellar/go/1.8.1/libexec/src/runtime/select.go:423 +0x1364
runtime.selectgo(0xc420040f50)
        /usr/local/Cellar/go/1.8.1/libexec/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
        /usr/local/Cellar/go/1.8.1/libexec/src/runtime/signal_unix.go:434 +0x2dd
runtime.goexit()
        /usr/local/Cellar/go/1.8.1/libexec/src/runtime/asm_amd64.s:2197 +0x1

goroutine 33 [semacquire, 3263 minutes]:                                                                                         [6/1199]sync.runtime_Semacquire(0xc4200109bc)
        /usr/local/Cellar/go/1.8.1/libexec/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc4200109b0)
        /usr/local/Cellar/go/1.8.1/libexec/src/sync/waitgroup.go:131 +0x7a
github.com/RichardKnop/machinery/v1/brokers.(*AMQPBroker).consume(0xc4200a8ec0, 0xc420083e60, 0xd8d1e0, 0xc4201644a0, 0xd8d160, 0xc420010480)
        /Users/lt/go/src/github.com/RichardKnop/machinery/v1/brokers/amqp.go:148 +0x3f1
github.com/RichardKnop/machinery/v1/brokers.(*AMQPBroker).StartConsuming(0xc4200a8ec0, 0xac51ef, 0x6, 0xd8d1e0, 0xc4201644a0, 0x0, 0x0, 0x0)
        /Users/lt/go/src/github.com/RichardKnop/machinery/v1/brokers/amqp.go:63 +0x437
github.com/RichardKnop/machinery/v1.(*Worker).Launch.func1(0xd977e0, 0xc4200a8ec0, 0xc4201644a0, 0xc420083c80)
        /Users/lt/go/src/github.com/RichardKnop/machinery/v1/worker.go:46 +0x63
created by github.com/RichardKnop/machinery/v1.(*Worker).Launch
        /Users/lt/go/src/github.com/RichardKnop/machinery/v1/worker.go:55 +0x3ce

goroutine 34 [chan send, 50 minutes]:
github.com/RichardKnop/machinery/v1/brokers.(*AMQPBroker).StopConsuming(0xc4200a8ec0)
        /Users/lt/go/src/github.com/RichardKnop/machinery/v1/brokers/amqp.go:72 +0x52
github.com/RichardKnop/machinery/v1.(*Worker).Quit(0xc4201644a0)
        /Users/lt/go/src/github.com/RichardKnop/machinery/v1/worker.go:69 +0x37
github.com/RichardKnop/machinery/v1.(*Worker).Launch.func2(0xc420083ce0, 0xc4201644a0, 0xc420083c80)
        /Users/lt/go/src/github.com/RichardKnop/machinery/v1/worker.go:60 +0x1a9
created by github.com/RichardKnop/machinery/v1.(*Worker).Launch
        /Users/lt/go/src/github.com/RichardKnop/machinery/v1/worker.go:62 +0x407

goroutine 82 [chan send, 3263 minutes]:
github.com/RichardKnop/machinery/v1/brokers.(*AMQPBroker).consume.func2(0xc4200109b0, 0xc4200a8ec0, 0xc4200c0a00, 0xd8d1e0, 0xc4201644a0, 0xc42006e4e0, 0x5, 0xc42006e480)
        /Users/lt/go/src/github.com/RichardKnop/machinery/v1/brokers/amqp.go:163 +0x15a
created by github.com/RichardKnop/machinery/v1/brokers.(*AMQPBroker).consume
        /Users/lt/go/src/github.com/RichardKnop/machinery/v1/brokers/amqp.go:170 +0x2ff

rax    0xfffffffffffffffc
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0xdcb018
rsi    0x0
rbp    0xc42003ded0
rsp    0xc42003de88
r8     0x0
r9     0x0
r10    0xc42003dec0
r11    0x246
r12    0x42d2d0
r13    0x34
r14    0x0
r15    0xf3
rip    0x4564d3
rflags 0x246
cs     0x33
fs     0x0
gs     0x0`

I am not sure what's happening, do you have any idea? thanks

**Comment by RichardKnop** [comment]
This might have been solved by this commit: https://github.com/RichardKnop/machinery/commit/bbdc469fc5ec89871a303ef2f6e33ad3f4ba89bd

Are you running latest code?

**Comment by saggit** [comment]
Yes, I try to solve it by use the latest code, but it still hangs, 
more detail, the problem will happen when worker idle for days.

**Comment by alieve** [comment]
It seems worker can not restore connection to Rabbit in case of loosing it and go to idle state. 
Steps to reproduce:
1. Run **worker.go worker** with configuration above, make sure rabbitmq-server is running
2. Stop rabbitmq-server
3. Start rabbitmq-server
4. Try to strike Ctr+C or send message by **worker.go send**. Nothing happens, worker in idle state and can be closed by killing process only.

**Comment by RichardKnop** [comment]
@saggit @alieve Can you pull from master and try now? I have pushed update which should fix this problem.

@alieve I have managed to reproduce the bug with steps you provided. I have updated code to fix this issue. Pull from master and try it. It should work now.

**Comment by saggit** [comment]
@RichardKnop Thanks for your hard work, But it will take me same time to verity due to #151 .

**Comment by saggit** [comment]
@RichardKnop I can confirm the issue was solved.

@alieve  what about you?
