### ISSUE TITLE
Error when pulling from Github (mongo client)

### ISSUE THREAD

**Issue by seonixx** [RichardKnop/machinery#383]
We've been using Machinery for some time - suddenly this morning all attempts to pull from github (go get -u) are resulting in:

> ../../../github.com/RichardKnop/machinery/v1/backends/mongo/mongodb.go:302:32: cannot use uri (type string) as type *options.ClientOptions in argument to mongo.NewClient

It's happening during download from Github, not during the Go build.

Can't see any changes recently in the repo (we successfully deployed yesterday).

Any ideas?

**Comment by seonixx** [comment]
Actually - can see a change was made in the last 24 hours...

https://github.com/RichardKnop/machinery/commit/be39d0b945df20dfff29c60ca79d91d7e452b4d2#diff-98c1e3afb4dd4a06358c9e96c3bd29aa

@RichardKnop are you seeing any issues here?

**Comment by RichardKnop** [comment]
@seonixx You are using master branch of github.com/mongodb/mongo-go-driver

In go.mod file we define version we are using: https://github.com/RichardKnop/machinery/blob/master/go.mod#L31

Which accepts string as input: https://github.com/mongodb/mongo-go-driver/blob/v0.3.0/mongo/client.go#L61

In master branch they have changed it: https://github.com/mongodb/mongo-go-driver/blob/master/mongo/client.go#L78

But machinery is not using that yet, we are still at previous version.

Are you using Go modules to handle dependencies? It's safest to use Go modules to use exactly same dependencies as CI is using for integration tests.

**Comment by RichardKnop** [comment]
I think you must be using some different way to manage dependencies and your Mongo library is latest code in their master branch in your vendor folder.

**Comment by Huangsir** [comment]
same problem

**Comment by owenhaynes** [comment]
fixed in #391 Just go around to updating to latest RC.

**Comment by joe-mcnuggets** [comment]
@RichardKnop it still doesn't work with dep:

```
dep ensure -update
```

hangs with subprocess calling ssh git@github.com git-upload-pack 'mongodb/specifications.git', strace on this subprocess says 

```
--- stopped by SIGTTOU ---
```
@owenhaynes can it be fixed without changing version constraints in dep to RC branches?

**Comment by owenhaynes** [comment]
This supports go modules, not dep. So if you will need to use a override at the moment, due to dep flaws.

This is what I am currently using with repos we still have which use dep.
[[override]]
  name = "go.mongodb.org/mongo-driver"
  version = ">=1.0.0-rc2"

I would also recommend never doing 
dep ensure -update
as it try to update everything and have had more problems with this, it's better todo 

dep ensure -update github.com/RichardKnop/machinery

**Comment by joe-mcnuggets** [comment]
@owenhaynes thank you!
